# Generated by Django 3.0.7 on 2020-07-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='culture',
            field=models.CharField(choices=[('GK', 'Greek'), ('R', 'Roman'), ('EG', 'Egyptian'), ('ET', 'Etruscan'), ('PH', 'Phoenician'), ('AN', 'Anatolian'), ('PR', 'Persian'), ('MC', 'Macedonian'), ('GA', 'Gallic'), ('HY', 'Hybrid'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
