# Generated by Django 3.0.7 on 2020-07-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_image_culture'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='period_prefix',
            field=models.CharField(choices=[('GN', 'General'), ('ER', 'Early'), ('MD', 'Middle'), ('LT', 'Late')], default='GN', max_length=2),
        ),
    ]
