# Generated by Django 3.0.7 on 2020-07-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_image_period_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='period',
            field=models.CharField(choices=[('BR', 'Bronze Age'), ('DK', 'Dark Age'), ('AC', 'Archai'), ('CL', 'Classical'), ('HL', 'Hellenistic'), ('EM', 'Etruscan/Monarchy'), ('RR', 'Roman Republic'), ('RE', 'Roman Empire'), ('LA', 'Late Antique'), ('PO', 'Other')], default='PO', max_length=2),
        ),
        migrations.AlterField(
            model_name='image',
            name='culture',
            field=models.CharField(choices=[('GK', 'Greek'), ('R', 'Roman'), ('EG', 'Egyptian'), ('ET', 'Etruscan'), ('PH', 'Phoenician'), ('AN', 'Anatolian'), ('PR', 'Persian'), ('MC', 'Macedonian'), ('GA', 'Gallic'), ('HY', 'Hybrid'), ('CO', 'Other')], default='CO', max_length=2),
        ),
    ]
