# Generated by Django 3.0.7 on 2020-07-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20200726_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='object_type',
            field=models.CharField(choices=[('VV', 'Vases & Vessels'), ('SB', 'Statues & Busts'), ('AS', 'Architectural Sculpture'), ('RS', 'Relief Sculpture'), ('IS', 'Inscriptions'), ('MS', 'Mosaics'), ('CS', 'Coins'), ('PT', 'Painting'), ('SC', 'Sarcophagus'), ('JB', 'Jewelry & Beauty'), ('TW', 'Tools & Weapons'), ('LP', 'Lamps'), ('FV', 'Figurines & Votives'), ('PP', 'Plans & Photos'), ('MR', 'Models & Reconstructions'), ('OO', 'Other')], default='OO', max_length=2),
        ),
    ]
