# Generated by Django 3.0.7 on 2020-07-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_image_object_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='vase_technique',
            field=models.CharField(blank=True, choices=[('HT', 'Hand-Thrown'), ('GM', 'Geometric'), ('BF', 'Black-Figure'), ('RF', 'Red-Figure'), ('SM', 'Stamped'), ('MM', 'Mold-Made'), ('UD', 'Undecorated'), ('TO', 'Other')], max_length=2),
        ),
    ]
