# Generated by Django 3.0.7 on 2020-07-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_image_vase_technique'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='material',
            field=models.CharField(choices=[('ST', 'Stone'), ('TC', 'Terracotta'), ('BN', 'Bone'), ('GL', 'Glass'), ('IV', 'Ivory'), ('WD', 'Wood'), ('FR', 'Fresco'), ('MG', 'Metal-Gold'), ('MS', 'Metal-Silver'), ('MO', 'Metal-Other'), ('OG', 'Organic'), ('NA', 'N/A'), ('OU', 'Other/Unknown')], default='OU', max_length=2),
        ),
        migrations.AddField(
            model_name='image',
            name='vase_shape',
            field=models.CharField(blank=True, choices=[('AMP', 'Amphora'), ('KRA', 'Krater'), ('HYD', 'Hydria'), ('KYL', 'Kylix'), ('PIT', 'Pithos'), ('KAN', 'Kantharos'), ('OLP', 'Olpe'), ('OIN', 'Oinochoe'), ('LEB', 'Lebes Gamikos'), ('PEL', 'Pelike'), ('STA', 'Stamnos'), ('DIN', 'Dinos'), ('PSY', 'Psykter'), ('PLA', 'Plate'), ('PHI', 'Phiale'), ('RHY', 'Rhyton'), ('MAS', 'Mastos'), ('SKY', 'Skyphos'), ('ALA', 'Alabastron'), ('ARY', 'Aryballos'), ('LEK', 'Lekythos'), ('LOU', 'Loutrophoros'), ('PYX', 'Pyxis'), ('VSO', 'Other')], max_length=3),
        ),
    ]
