# Generated by Django 3.0.7 on 2020-07-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_image_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='artist_or_attribution',
            field=models.CharField(default='none entered', max_length=150),
            preserve_default=False,
        ),
    ]
