# Generated by Django 3.0.7 on 2020-07-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_image_artist_or_attribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='associated_building',
            field=models.CharField(blank=True, choices=[('MY', 'Mycenae'), ('AA', 'Athenian Acropolis'), ('PR', 'Parthenon'), ('PN', 'Pantheon'), ('AG', 'Altar of the Gods (Pergamon)'), ('EP', 'Ephesos'), ('AD', 'Aphrodisias'), ('SB', 'Sebasteion (Aphrodisias)'), ('PG', 'Pergamon'), ('PE', 'Perge'), ('SG', 'Sagalassos'), ('TZ', 'Temple of Zeus (Olympia)'), ('OA', 'Olympia'), ('CR', 'Corinth'), ('RF', 'Roman Forum'), ('AT', 'Athens'), ('RM', 'Rome'), ('PI', 'Pompeii'), ('AP', 'Ara Pacis')], max_length=2),
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(default='No description added'),
        ),
        migrations.AddField(
            model_name='image',
            name='subject',
            field=models.CharField(blank=True, choices=[('MY', 'Myth'), ('DL', 'Daily Life'), ('PL', 'Politics'), ('RT', 'Ritual'), ('DC', 'Decorative'), ('ML', 'Military'), ('FN', 'Funerary')], max_length=2),
        ),
    ]
