# Generated by Django 3.0.7 on 2020-07-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_auto_20200727_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='museum_collection',
            field=models.CharField(blank=True, choices=[('ANM', 'Athens National Museum'), ('AAM', 'Athenian Acropolis Museum'), ('GTV', 'Getty Villa'), ('SAM', 'San Antonio Museum of Art'), ('CPM', 'Capitoline Museum'), ('MMI', 'Montemartini (Rome)'), ('ATK', 'Antakya'), ('ANT', 'Antalya'), ('OLY', 'Olympia'), ('APH', 'Aphrodisas'), ('EPH', 'Ephesos'), ('COR', 'Corinth'), ('IST', 'Istanbul'), ('IMA', 'Isthmia'), ('NMA', 'Nemea'), ('PMB', 'Pergamon Museum (Berlin)'), ('SVL', 'Seville'), ('HGE', 'Houston Gladiator Exhibit'), ('VTM', 'Vatican Museum'), ('ZGM', 'Zeugma'), ('MYC', 'Mycenae'), ('DEL', 'Delphi'), ('ELE', 'Eleusis'), ('HPS', 'Hierapolis'), ('BMA', 'Bergama'), ('PLA', 'Pella'), ('VGA', 'Vergina'), ('IZM', 'Izmir'), ('EPI', 'Epidauros'), ('BMF', 'Boston Museum of Fine Arts'), ('SAG', 'Sagalassos')], max_length=3),
        ),
        migrations.AlterField(
            model_name='image',
            name='artist_or_attribution',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
