# Generated by Django 3.0.7 on 2020-07-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_auto_20200727_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='incomplete_info',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='image',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
