# Generated by Django 3.0.7 on 2020-07-27 01:02

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0017_auto_20200727_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='image',
            name='culture',
            field=models.CharField(blank=True, choices=[('GK', 'Greek'), ('R', 'Roman'), ('EG', 'Egyptian'), ('ET', 'Etruscan'), ('PH', 'Phoenician'), ('AN', 'Anatolian'), ('PR', 'Persian'), ('MC', 'Macedonian'), ('GA', 'Gallic'), ('HY', 'Hybrid'), ('CO', 'Other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='image',
            name='material',
            field=models.CharField(blank=True, choices=[('ST', 'Stone'), ('TC', 'Terracotta'), ('BN', 'Bone'), ('GL', 'Glass'), ('IV', 'Ivory'), ('WD', 'Wood'), ('FR', 'Fresco'), ('MG', 'Metal-Gold'), ('MS', 'Metal-Silver'), ('MO', 'Metal-Other'), ('OG', 'Organic'), ('NA', 'N/A'), ('OU', 'Other/Unknown')], max_length=2),
        ),
        migrations.AlterField(
            model_name='image',
            name='object_type',
            field=models.CharField(blank=True, choices=[('VV', 'Vases & Vessels'), ('SB', 'Statues & Busts'), ('AS', 'Architectural Sculpture'), ('RS', 'Relief Sculpture'), ('IS', 'Inscriptions'), ('MS', 'Mosaics'), ('CS', 'Coins'), ('PT', 'Painting'), ('SC', 'Sarcophagus'), ('JB', 'Jewelry & Beauty'), ('TW', 'Tools & Weapons'), ('LP', 'Lamps'), ('FV', 'Figurines & Votives'), ('PP', 'Plans & Photos'), ('MR', 'Models & Reconstructions'), ('OO', 'Other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='image',
            name='period',
            field=models.CharField(blank=True, choices=[('BR', 'Bronze Age'), ('DK', 'Dark Age'), ('AC', 'Archai'), ('CL', 'Classical'), ('HL', 'Hellenistic'), ('EM', 'Etruscan/Monarchy'), ('RR', 'Roman Republic'), ('RE', 'Roman Empire'), ('LA', 'Late Antique'), ('PO', 'Other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='image',
            name='period_prefix',
            field=models.CharField(blank=True, choices=[('GN', 'General'), ('ER', 'Early'), ('MD', 'Middle'), ('LT', 'Late')], max_length=2),
        ),
    ]
