# Generated by Django 3.0.7 on 2020-07-31 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0018_auto_20200727_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='associated_building',
            field=models.CharField(blank=True, choices=[('MY', 'Mycenae'), ('AA', 'Athenian Acropolis'), ('PR', 'Parthenon'), ('PN', 'Pantheon'), ('AG', 'Altar of the Gods (Pergamon)'), ('EP', 'Ephesos'), ('AD', 'Aphrodisias'), ('SB', 'Sebasteion (Aphrodisias)'), ('PG', 'Pergamon'), ('PE', 'Perge'), ('SG', 'Sagalassos'), ('TZ', 'Temple of Zeus (Olympia)'), ('OA', 'Olympia'), ('CR', 'Corinth'), ('RF', 'Roman Forum'), ('AT', 'Athens'), ('RM', 'Rome'), ('PI', 'Pompeii'), ('AP', 'Ara Pacis'), ('BO', 'Other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='museum_collection',
            field=models.CharField(blank=True, choices=[('ANM', 'Athens National Museum'), ('AAM', 'Athenian Acropolis Museum'), ('GTV', 'Getty Villa'), ('SAM', 'San Antonio Museum of Art'), ('CPM', 'Capitoline Museum'), ('MMI', 'Montemartini (Rome)'), ('ATK', 'Antakya'), ('ANT', 'Antalya'), ('OLY', 'Olympia'), ('APH', 'Aphrodisas'), ('EPH', 'Ephesos'), ('COR', 'Corinth'), ('IST', 'Istanbul'), ('IMA', 'Isthmia'), ('NMA', 'Nemea'), ('PMB', 'Pergamon Museum (Berlin)'), ('SVL', 'Seville'), ('HGE', 'Houston Gladiator Exhibit'), ('VTM', 'Vatican Museum'), ('ZGM', 'Zeugma'), ('MYC', 'Mycenae'), ('DEL', 'Delphi'), ('ELE', 'Eleusis'), ('HPS', 'Hierapolis'), ('BMA', 'Bergama'), ('PLA', 'Pella'), ('VGA', 'Vergina'), ('IZM', 'Izmir'), ('EPI', 'Epidauros'), ('BMF', 'Boston Museum of Fine Arts'), ('SAG', 'Sagalassos'), ('MUO', 'Other')], max_length=3),
        ),
        migrations.AlterField(
            model_name='image',
            name='subject',
            field=models.CharField(blank=True, choices=[('MY', 'Myth'), ('DL', 'Daily Life'), ('PL', 'Politics'), ('RT', 'Ritual'), ('DC', 'Decorative'), ('ML', 'Military'), ('FN', 'Funerary'), ('SO', 'Other')], max_length=2),
        ),
    ]
