# Generated by Django 3.0.7 on 2020-07-31 17:37

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0019_auto_20200731_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='artist_or_attribution',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='associated_building',
            field=models.CharField(blank=True, choices=[('MY', 'Mycenae'), ('AA', 'Athenian Acropolis'), ('PR', 'Parthenon'), ('PN', 'Pantheon'), ('AG', 'Altar of the Gods (Pergamon)'), ('EP', 'Ephesos'), ('AD', 'Aphrodisias'), ('SB', 'Sebasteion (Aphrodisias)'), ('PG', 'Pergamon'), ('PE', 'Perge'), ('SG', 'Sagalassos'), ('TZ', 'Temple of Zeus (Olympia)'), ('OA', 'Olympia'), ('CR', 'Corinth'), ('RF', 'Roman Forum'), ('AT', 'Athens'), ('RM', 'Rome'), ('PI', 'Pompeii'), ('AP', 'Ara Pacis'), ('BO', 'Other')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='culture',
            field=models.CharField(blank=True, choices=[('GK', 'Greek'), ('R', 'Roman'), ('EG', 'Egyptian'), ('ET', 'Etruscan'), ('PH', 'Phoenician'), ('AN', 'Anatolian'), ('PR', 'Persian'), ('MC', 'Macedonian'), ('GA', 'Gallic'), ('HY', 'Hybrid'), ('CO', 'Other')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='material',
            field=models.CharField(blank=True, choices=[('ST', 'Stone'), ('TC', 'Terracotta'), ('BN', 'Bone'), ('GL', 'Glass'), ('IV', 'Ivory'), ('WD', 'Wood'), ('FR', 'Fresco'), ('MG', 'Metal-Gold'), ('MS', 'Metal-Silver'), ('MO', 'Metal-Other'), ('OG', 'Organic'), ('NA', 'N/A'), ('OU', 'Other/Unknown')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='museum_collection',
            field=models.CharField(blank=True, choices=[('ANM', 'Athens National Museum'), ('AAM', 'Athenian Acropolis Museum'), ('GTV', 'Getty Villa'), ('SAM', 'San Antonio Museum of Art'), ('CPM', 'Capitoline Museum'), ('MMI', 'Montemartini (Rome)'), ('ATK', 'Antakya'), ('ANT', 'Antalya'), ('OLY', 'Olympia'), ('APH', 'Aphrodisas'), ('EPH', 'Ephesos'), ('COR', 'Corinth'), ('IST', 'Istanbul'), ('IMA', 'Isthmia'), ('NMA', 'Nemea'), ('PMB', 'Pergamon Museum (Berlin)'), ('SVL', 'Seville'), ('HGE', 'Houston Gladiator Exhibit'), ('VTM', 'Vatican Museum'), ('ZGM', 'Zeugma'), ('MYC', 'Mycenae'), ('DEL', 'Delphi'), ('ELE', 'Eleusis'), ('HPS', 'Hierapolis'), ('BMA', 'Bergama'), ('PLA', 'Pella'), ('VGA', 'Vergina'), ('IZM', 'Izmir'), ('EPI', 'Epidauros'), ('BMF', 'Boston Museum of Fine Arts'), ('SAG', 'Sagalassos'), ('MUO', 'Other')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='object_type',
            field=models.CharField(blank=True, choices=[('VV', 'Vases & Vessels'), ('SB', 'Statues & Busts'), ('AS', 'Architectural Sculpture'), ('RS', 'Relief Sculpture'), ('IS', 'Inscriptions'), ('MS', 'Mosaics'), ('CS', 'Coins'), ('PT', 'Painting'), ('SC', 'Sarcophagus'), ('JB', 'Jewelry & Beauty'), ('TW', 'Tools & Weapons'), ('LP', 'Lamps'), ('FV', 'Figurines & Votives'), ('PP', 'Plans & Photos'), ('MR', 'Models & Reconstructions'), ('OO', 'Other')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='period',
            field=models.CharField(blank=True, choices=[('BR', 'Bronze Age'), ('DK', 'Dark Age'), ('AC', 'Archai'), ('CL', 'Classical'), ('HL', 'Hellenistic'), ('EM', 'Etruscan/Monarchy'), ('RR', 'Roman Republic'), ('RE', 'Roman Empire'), ('LA', 'Late Antique'), ('PO', 'Other')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='period_prefix',
            field=models.CharField(blank=True, choices=[('GN', 'General'), ('ER', 'Early'), ('MD', 'Middle'), ('LT', 'Late')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='subject',
            field=models.CharField(blank=True, choices=[('MY', 'Myth'), ('DL', 'Daily Life'), ('PL', 'Politics'), ('RT', 'Ritual'), ('DC', 'Decorative'), ('ML', 'Military'), ('FN', 'Funerary'), ('SO', 'Other')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='vase_shape',
            field=models.CharField(blank=True, choices=[('AMP', 'Amphora'), ('KRA', 'Krater'), ('HYD', 'Hydria'), ('KYL', 'Kylix'), ('PIT', 'Pithos'), ('KAN', 'Kantharos'), ('OLP', 'Olpe'), ('OIN', 'Oinochoe'), ('LEB', 'Lebes Gamikos'), ('PEL', 'Pelike'), ('STA', 'Stamnos'), ('DIN', 'Dinos'), ('PSY', 'Psykter'), ('PLA', 'Plate'), ('PHI', 'Phiale'), ('RHY', 'Rhyton'), ('MAS', 'Mastos'), ('SKY', 'Skyphos'), ('ALA', 'Alabastron'), ('ARY', 'Aryballos'), ('LEK', 'Lekythos'), ('LOU', 'Loutrophoros'), ('PYX', 'Pyxis'), ('VSO', 'Other')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='vase_technique',
            field=models.CharField(blank=True, choices=[('HT', 'Hand-Thrown'), ('GM', 'Geometric'), ('BF', 'Black-Figure'), ('RF', 'Red-Figure'), ('SM', 'Stamped'), ('MM', 'Mold-Made'), ('UD', 'Undecorated'), ('TO', 'Other')], max_length=2, null=True),
        ),
    ]
