# Generated by Django 3.0.7 on 2020-07-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0020_auto_20200731_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(default='No description added', null=True),
        ),
    ]
