# Generated by Django 3.0.7 on 2020-08-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0021_auto_20200731_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='material',
            field=models.CharField(blank=True, choices=[('ST', 'Stone'), ('TC', 'Terracotta'), ('BN', 'Bone'), ('GL', 'Glass'), ('IV', 'Ivory'), ('WD', 'Wood'), ('FR', 'Fresco'), ('MR', 'Marble'), ('MB', 'Marble-Bronze'), ('ML', 'Marble-Lead'), ('MG', 'Metal-Gold'), ('MS', 'Metal-Silver'), ('MO', 'Metal-Other'), ('OG', 'Organic'), ('NA', 'N/A'), ('OU', 'Other/Unknown')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='period',
            field=models.CharField(blank=True, choices=[('BR', 'Bronze Age'), ('IG', 'Iron Age/Early Greek'), ('AC', 'Archaic'), ('CL', 'Classical'), ('HL', 'Hellenistic'), ('EM', 'Etruscan/Monarchy'), ('RR', 'Roman Republic'), ('RE', 'Roman Empire'), ('LA', 'Late Antique'), ('PO', 'Other')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='image',
            name='vase_technique',
            field=models.CharField(blank=True, choices=[('GM', 'Geometric/Proto-Geometric'), ('BF', 'Black-Figure'), ('RF', 'Red-Figure'), ('WG', 'White-Ground'), ('MM', 'Mold-Made'), ('SM', 'Stamped'), ('UD', 'Undecorated'), ('CW', 'Cookware'), ('HT', 'Hand-Thrown'), ('TO', 'Other')], max_length=2, null=True),
        ),
    ]
