# Generated by Django 3.0.7 on 2020-08-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0023_auto_20200803_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Specific Date(s)'),
        ),
    ]
