# Generated by Django 3.0.7 on 2020-08-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0024_auto_20200803_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='associated_site',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='associated_building',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
